### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by dklesev** [wuziheng/SiliconWaferDefectDetection#1]
I get this when trying `python test.py`:

```
2017-09-14 21:19:55,919: INFO     image_process        : Semilab261151217B-1457
2017-09-14 21:19:55,919: INFO     image_process        : DETECTION STARTS:

Traceback (most recent call last):
  File "test.py", line 92, in <module>
    image_process(src_dict[test_name], test_name)
  File "test.py", line 33, in image_process
    _target_contour = cv3.find_target_contour(_threshold_image)
  File "/tmp/SiliconWaferDefectDetection/util/cv_wzh.py", line 47, in find_target_contour
    contours, _ = cv2.findContours(src, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
ValueError: too many values to unpack
```

**Comment by wuziheng** [comment]
findContours return depends on the version of OpenCV
using help(cv2.findContours)　in python environment to  varify the number of parameters returned  and rewrite this code 
"contours, _ = cv2.findContours(src, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)"

**Comment by wuziheng** [comment]
I have already answered on github,you can check the cv2.findContours return parameter's num and rewrite this '_target_contour = cv3.find_target_contour(_threshold_image)'


------------------ Original ------------------
